<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

add_action('genesis_meta', 'phone_date_address_email', 15);
function phone_date_address_email(){
	?>
	<!-- Remove Microsoft Edge's & Safari phone-date-address-email styling -->
	<meta name="format-detection" content="telephone=no">
	<meta name="format-detection" content="date=no">
	<meta name="format-detection" content="address=no">
	<meta name="format-detection" content="email=no">
	<?php
}

do_action( 'genesis_doctype' );
do_action( 'genesis_title' );
do_action( 'genesis_meta' );
wp_head(); // We need this for plugins.
?>
<!-- if it is not the home page make the header image have a smaller height -->
<?php if ( !is_front_page()) { ?>

<style>
body .site-header .header-wrap {
    min-height: 433px;
    position: relative;
    padding-bottom: 100px;
    z-index: 10;
}
</style>

<?php } ?>
</head>
<?php
genesis_markup( array(
	'open'   => '<body %s>',
	'context' => 'body',
) );
do_action( 'genesis_before' );

genesis_markup( array(
	'open'   => '<div %s>',
	'context' => 'site-container',
) );

do_action( 'genesis_before_header' );
do_action( 'genesis_header' );
do_action( 'genesis_after_header' );

genesis_markup( array(
	'open'   => '<div %s>',
	'context' => 'container',
) );

genesis_structural_wrap( 'container' );
