<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

// This file handles single entries, but only exists for the sake of child theme forward compatibility.

add_shortcode( 'custom_post_tags', 'custom_post_tags_shortcode' );
function custom_post_tags_shortcode( $atts ) {
	$defaults = array(
		'after'  => '',
		'before' => '<span>'.__( 'Tags', 'genesis' ).'</span>',
		'sep'    => ', ',
	);
	$atts = shortcode_atts( $defaults, $atts, 'post_tags' );

	$tags = get_the_tag_list( $atts['before'], trim( $atts['sep'] ) . ' ', $atts['after'] );

	// Do nothing if no tags.
	if ( ! $tags ) {
		return '';
	}

	if ( genesis_html5() ) {
		$output = sprintf( '<span %s>', genesis_attr( 'entry-tags' ) ) . $tags . '</span>';
	} else {
		$output = '<span class="tags">' . $tags . '</span>';
	}

	return apply_filters( 'custom_post_tags_shortcode', $output, $atts );

}
add_shortcode( 'custom_post_categories', 'custom_post_categories_shortcode' );
function custom_post_categories_shortcode( $atts ) {

	$defaults = array(
		'sep'    => ', ',
		'before' => '<span>'.__( 'Category', 'genesis' ).'</span>',
		'after'  => '',
	);

	$atts = shortcode_atts( $defaults, $atts, 'custom_post_categories' );

	$cats = get_the_category_list( trim( $atts['sep'] ) . ' ' );

	// Do nothing if there are no categories.
	if ( ! $cats ) {
		return '';
	}

	if ( genesis_html5() ) {
		$output = sprintf( '<span %s>', genesis_attr( 'entry-categories' ) ) . $atts['before'] . $cats . $atts['after'] . '</span>';
	} else {
		$output = '<span class="categories">' . $atts['before'] . $cats . $atts['after'] . '</span>';
	}

	return apply_filters( 'custom_post_categories_shortcode', $output, $atts );

}
remove_action('genesis_entry_footer', 'genesis_post_meta');
add_action( 'genesis_entry_footer', 'custom_post_meta', 10);
function custom_post_meta(){

	if(!post_type_supports(get_post_type(), 'genesis-entry-meta-after-content')){
		return;
	}
	$filtered = apply_filters( 'genesis_post_meta', '[custom_post_categories] [custom_post_tags]' );

	if(false == trim($filtered)){
		return;
	}

	$output = genesis_markup(array(
		'open'    => '<p %s>',
		'close'   => '</p>',
		'content' => genesis_strip_p_tags($filtered),
		'context' => 'entry-meta-after-content',
	));
}
remove_action( 'genesis_entry_header', 'genesis_post_info', 12);
genesis();
